### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by OleksiySitka** [YunoHost-Apps/reel2bits_ynh#12]
Hi! I tried to install this on YunoHost 3.5.2.2 (stable) and "﻿﻿The operation 'Install 'reel2bits' application' has failed!". Here's the log:
> 2019-06-10 13:35:48,685: DEBUG - [  1%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o
> 2019-06-10 13:44:15,018: DEBUG - googlemock/CMakeFiles/gmock_main.dir/build.make:62: recipe for target 'googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o' failed
> 2019-06-10 13:44:15,020: WARNING - c++: internal compiler error: Killed (program cc1plus)
> 2019-06-10 13:44:15,024: DEBUG - CMakeFiles/Makefile2:227: recipe for target 'googlemock/CMakeFiles/gmock_main.dir/all' failed
> 2019-06-10 13:44:15,024: WARNING - Please submit a full bug report,
> 2019-06-10 13:44:15,024: DEBUG - Makefile:160: recipe for target 'all' failed
> 2019-06-10 13:44:15,024: WARNING - with preprocessed source if appropriate.
> 2019-06-10 13:44:15,025: DEBUG - + ynh_exit_properly
> 2019-06-10 13:44:15,025: WARNING - See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
> 2019-06-10 13:44:15,025: DEBUG - + local exit_code=2
> 2019-06-10 13:44:15,025: WARNING - make[2]: *** [googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o] Error 4
> 2019-06-10 13:44:15,025: DEBUG - + '[' 2 -eq 0 ']'
> 2019-06-10 13:44:15,025: WARNING - make[1]: *** [googlemock/CMakeFiles/gmock_main.dir/all] Error 2
> 2019-06-10 13:44:15,026: DEBUG - + trap '' EXIT
> 2019-06-10 13:44:15,026: WARNING - make: *** [all] Error 2
> 2019-06-10 13:44:15,026: DEBUG - + set +eu
> 2019-06-10 13:44:15,026: WARNING - !!
> 2019-06-10 13:44:15,027: DEBUG - + echo -e '!!\n  reel2bits'\''s script has encountered an error. Its execution was cancelled.\n!!'
> 2019-06-10 13:44:15,027: WARNING -   reel2bits's script has encountered an error. Its execution was cancelled.
> 2019-06-10 13:44:15,028: DEBUG - + type -t ynh_clean_setup
> 2019-06-10 13:44:15,028: WARNING - !!
> 2019-06-10 13:44:15,031: DEBUG - + ynh_clean_setup
> 2019-06-10 13:44:15,031: DEBUG - + ynh_clean_check_starting
> 2019-06-10 13:44:15,031: DEBUG - + kill -s 15
> 2019-06-10 13:44:15,032: DEBUG - kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
> 2019-06-10 13:44:15,032: DEBUG - + ynh_secure_remove ''
> 2019-06-10 13:44:15,035: DEBUG - + local legacy_args=f
> 2019-06-10 13:44:15,035: DEBUG - + args_array=([f]=file=)
> 2019-06-10 13:44:15,038: DEBUG - + declare -Ar args_array
> 2019-06-10 13:44:15,039: DEBUG - + local file
> 2019-06-10 13:44:15,040: DEBUG - + ynh_handle_getopts_args ''
> 2019-06-10 13:44:15,041: DEBUG - + set +x
> 2019-06-10 13:44:15,142: DEBUG - + echo '! Helper used in legacy mode !'
> 2019-06-10 13:44:15,142: WARNING - 
> 2019-06-10 13:44:15,142: DEBUG - + set +x
> 2019-06-10 13:44:15,143: DEBUG - + local 'forbidden_path= 	/var/www 	/home/yunohost.app'
> 2019-06-10 13:44:15,143: DEBUG - + '[' 1 -ge 2 ']'
> 2019-06-10 13:44:15,143: DEBUG - + [[  	/var/www 	/home/yunohost.app =~ '' ]]
> 2019-06-10 13:44:15,143: DEBUG - + echo 'Avoid deleting .'
> 2019-06-10 13:44:15,143: DEBUG - Avoid deleting .
> 2019-06-10 13:44:15,143: DEBUG - + ynh_die
> 2019-06-10 13:44:15,143: DEBUG - + local legacy_args=mc
> 2019-06-10 13:44:15,143: DEBUG - + args_array=([m]=message= [c]=ret_code=)
> 2019-06-10 13:44:15,143: DEBUG - + declare -Ar args_array
> 2019-06-10 13:44:15,144: DEBUG - + local message
> 2019-06-10 13:44:15,144: DEBUG - + local ret_code
> 2019-06-10 13:44:15,144: DEBUG - + ynh_handle_getopts_args
> 2019-06-10 13:44:15,144: DEBUG - + set +x
> 2019-06-10 13:44:15,144: DEBUG - + echo ''
> 2019-06-10 13:44:15,144: DEBUG - + exit 1

**Comment by yalh76** [comment]
Just tested the install on a fresh Yunohost and install is working.

Can you provide the link to the logs after executing: `yunohost app install https://github.com/YunoHost-Apps/reel2bits_ynh --debug`

**Comment by OleksiySitka** [comment]
Here you go
https://pastebin.com/GeGDxvSV
It ended up with ` ERROR The operation 'Install 'reel2bits' application' has failed! To get help, please share the full log of this operation using the command 'yunohost log display 20190611-080233-app_install-reel2bits --share'` which returned this link https://paste.yunohost.org/raw/mirikawase

**Comment by yalh76** [comment]
Ok, so your problem is:

`136838 WARNING virtual memory exhausted: Cannot allocate memory`

during the build of audiowaveform, the application that generates waveform data from the audio file.

I added in the swap branch a 2048 Mo swap file if you can test to install using :
`yunohost app install https://github.com/YunoHost-Apps/reel2bits_ynh/tree/swap --debug`

And let me know if it works and if it's enough memory

**Comment by OleksiySitka** [comment]
Yep, this one worked. Thanks
