### ISSUE TITLE
Yuno Host breaks after uninstalling

### ISSUE THREAD

**Issue by OleksiySitka** [YunoHost-Apps/reel2bits_ynh#15]
Hi! After testing the version with a bigger swap from [issue #12](https://github.com/YunoHost-Apps/reel2bits_ynh/issues/12) I wanted to reinstall this app on a different domain so I uninstalled it and after that my Yuno Host instance stopped working properly and seems to have some issues with memory. Here's an example log https://pastebin.com/FBTkWsb4
Also mysql fails to start and sometimes I catch something like `nginx: [alert] mmap(MAP_ANON|MAP_SHARED, 52428800) failed (12: Cannot allocate memory)`

Do you think this might be related to uninstall of reel2bits_ynh, or is it a coincidence?

**Comment by yalh76** [comment]
I think it's not related. I made some test on a fresh Yunohost:

1. Before installing reel2bits:
```
$ cat /proc/swaps
Filename                                Type            Size    Used    Priority
/dev/dm-2                               partition       8384508 463520  -1
```

2. After installing reel2bits:
```
$ cat /proc/swaps
Filename                                Type            Size    Used    Priority
/dev/dm-2                               partition       8384508 788588  -1
/swap_reel2bits                         file            2097148 0       -2
```

3. After removing reel2bits:
```
$ cat /proc/swaps
Filename                                Type            Size    Used    Priority
/dev/dm-2                               partition       8384508 793996  -1
```
