### ISSUE TITLE
Failed install on Yunohost 3,6,4

### ISSUE THREAD

**Issue by unklebonehead** [YunoHost-Apps/reel2bits_ynh#20]
Install failed twice. I'm a novice and dont know what I'm doing.
https://paste.yunohost.org/raw/zihohitoke

**Comment by yalh76** [comment]
other topic: https://forum.yunohost.org/t/reel2bits-failed-install/8374

**Comment by yalh76** [comment]
I will look at that and let you know

**Comment by unklebonehead** [comment]
Thank you.

**Comment by yalh76** [comment]
It seems you have an issue with the HOME variable, what is the result if you execute `echo $HOME` from the command line ?

**Comment by unklebonehead** [comment]
/home/admin
I was installing from the web interface but I dont think that would make a difference.

**Comment by yalh76** [comment]
On wath kind of material are you installing reel2bits ?

**Comment by nathancmcrae** [comment]
I just had the same issue installing via the web interface, but installing from CLI worked.

Failed install log: https://paste.yunohost.org/raw/jedakajexi

**Comment by unklebonehead** [comment]
> On wath kind of material are you installing reel2bits ?

Yunohost3.6.4 through the admin panel.

**Comment by unklebonehead** [comment]
Just did it again. 
https://paste.yunohost.org/raw/rixoxoxexa
I have been getting a "The yaml metadata file associated with logs is corrupted: '{md_file}'" error here recently. I have no idea what that means. I asked on the forum and nobody has had time to look at it yet. Could that be the problem?

**Comment by yalh76** [comment]
Can you try to install reel2bits from the command line ?

**Comment by unklebonehead** [comment]
Just want to confirm the command before doing it.
sudo yunohost app install https://github.com/Yunohost-Apps/reel2bits_ynh
Is that the correct one or should I do the testing one?

**Comment by unklebonehead** [comment]
Well I tried that command. It got stuck for over an hour and 15 minutes. Heres is copy and paste from terminal before I ctrl c so I could go do the day job.
```

admin@ubmedia:~$ sudo yunohost app install https://github.com/Yunohost-Apps/reel2bits_ynh
WARNING! Installing 3rd party applications may compromise the integrity and security of your system. You should probably NOT install it unless you know what you are doing. Are you willing to take that risk? [Y/N] : y
Available domains:
- ntroradio.com
- boneheadmedia.com
- ubmedia.nohost.me
- admin.ntroradio.com
- posts.boneheadmedia.com
- peertube.boneheadmedia.com
- funkwhale.boneheadmedia.com
- reel2bits.boneheadmedia.com
Choose a domain name for ynhexample (default: ubmedia.nohost.me): reel2bits.boneheadmedia.com
Available users:
- unklebonehead
- unkleb
Choose an admin user: unklebonehead
Is it a public application? [yes | no] (default: yes): yes
Choose the application language [fr | en] (default: en): en
You are now about to define a new user password. The password should be at least 8 characters - though it is good practice to use longer password (i.e. a passphrase) and/or to use various kind of characters (uppercase, lowercase, digits and special characters).
Set the administrator password: 
Info: Installing application reel2bits…
Info: Validating installation parameters...
Info: Storing installation settings...
Info: Configuring firewall...
Info: Installing build dependencies...
Extracting templates from packages: 100%
Info: Adding 2048 Mo to swap...
Warning: fallocate: fallocate failed: Operation not supported
Warning: 2097152+0 records in
Warning: 2097152+0 records out
Warning: 2147483648 bytes (2.1 GB, 2.0 GiB) copied, 30.7326 s, 69.9 MB/s
Info: Building audiowaveform...
Warning: [WARN] Avoid deleting /var/www/reel2bits/audiowaveform.d/.
Info: Removing build dependencies
Info: Installing dependencies...
Extracting templates from packages: 100%
Info: Creating a PostgreSQL database...
Info: Setting up source files...
Info: Configuring nginx web server...
Info: Configuring system user...
Info: Create the data directory...
Warning: WARNING: Unsupported Python version: `3.7.4`, trying with the following URL anyway: http://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz
Warning: /usr/lib/python3/dist-packages/virtualenv.py:1086: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Warning:   import imp
Warning:   Running command git clone -q https://github.com/jwag956/flask-security /tmp/pip-install-n6vvkj_9/Flask-Security-too
```

**Comment by yalh76** [comment]
Well... installation can took a lot of time, better to let it install until the end.

**Comment by unklebonehead** [comment]
FINALLY SUCCESS!!!
I did have 3 upgrades that needed to be done on my Yunohost. But waited till after the upgrades and then did it through the command line. Then just left it alone for about an hour. Came back and it was done. 
The post install command wouldnt work to create user. But I was able to create a user through the instance.
