### ISSUE TITLE
Well Crap Now getting this when trying to createyser

### ISSUE THREAD

**Issue by unklebonehead** [YunoHost-Apps/reel2bits_ynh#23]
No Sentry Flask/Celery support available
I was able to create a user through the register page.
Does not see me as admin though

**Comment by unklebonehead** [comment]
I guess it did work. I now see that my user can see the log files. 
I'm guessing that is what it means to be admin?

**Comment by yalh76** [comment]
As written in the read me:
When your Reel2Bits instance is installed, you need to execute the following command to create a first user and give it admin rights: (cd /var/www/reel2bits && ve3/bin/flask createuser)
